apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: vsr-app-dev
  namespace: app-dev
spec:
  host: cafeshop.giri.local
  upstreams:
  - name: coffee
    service: coffee
    port: 8082
  subroutes:
  - path: /
    action:
     pass: coffee
  
