apiVersion: appprotect.f5.com/v1beta1
kind: APLogConf
metadata:
  name: appdev-aplogconf
  namespace: secops
spec:
  filter:
    request_type: all
  content:
    format: user-defined
    format_string: >-
             { "violations" : "%violations%","signature_ids" : "%sig_ids%", "violation_details" : "%violation_details%" }
    max_request_size: any
    max_message_size: 50k
