apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: tea-vsr
  namespace: app-dev-tea
spec:
  host: cafeshop.giri.local
  upstreams:
  - name: tea
    service: tea
    port: 8081
  subroutes:
  - path: /api/v1/tea
    action:
     pass: tea
  
