---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nicadmin-CR
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs: ["*"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings 
  verbs: ["*"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nicadmin-CRB
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nicadmin-CR
subjects:
- kind: User
  name: "nicadmin.foo.bang"
  apiGroup: rbac.authorization.k8s.io
