apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: cafeshop-policy
  namespace: nginx-ingress
spec:
  waf:
    enable: true
    apPolicy: "nginx-ingress/cafeshop-appolicy"
    securityLogs:
    - enable: true
      apLogConf: "nginx-ingress/cafeshop-aplogconf"
      logDest: "stderr"
