apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: vsr-cafeshop
  namespace: app-dev-cafeshop
spec:
  host: cafeshop.giri.local
  upstreams:
  - name: cafeshop
    service: cafeshop
    port: 80
  subroutes:
  - path: /
    action:
     pass: cafeshop
  
