# Date: Feb-2023 Deployment "coffee" imageID: docker pull giriraj789/cafeshop:v1 
# 8082 --> {"Service":"COFFEE"}
# 8082/api/v1/coffee --> {"service":"COFFEE-v1"}
# 8082/api/v2/coffee --> {"service":"COFFEE-v2"}
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-dev-coffee
  labels:
    istio-injection: disabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: app-dev-coffee
  labels:
    app: coffee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: giriraj789/cafeshop:v1
        resources:
            limits:
              memory: 200Mi
              cpu: 300m
            requests:
              memory: 100Mi
              cpu: 200m
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: coffee
  namespace: app-dev-coffee
spec:
  selector:
    app: coffee
  ports:
    - name: http-coffee
      port: 8082
      targetPort: 8082
      protocol: TCP
