---
apiVersion: v1
kind: Service
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: https-nic
    namespace: nic
  spec:
    ports:
    - nodePort: 30643
      port: 443
      protocol: TCP
      targetPort: 443
    selector:
       app.kubernetes.io/instance: my
    type: NodePort
  status:
    loadBalancer: {}
---
apiVersion: v1
kind: Service
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: http-nic
    namespace: nic
  spec:
    ports:
    - nodePort: 30680
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
       app.kubernetes.io/instance: my
    type: NodePort
  status:
    loadBalancer: {}
---
