--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: db
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: db
  template: 
    metadata: 
      labels: 
        app: db
    spec: 
      containers: 
        - 
          image: "docker.io/giriraj789/mysql:codestdcode"
          name: db
          ports: 
            - 
              containerPort: 3306
