# Date: Feb-2023 Deployment "tea" imageID: docker pull giriraj789/cafeshop:v1 
# 8081 --> {"Service":"TEA"}
# 8081/api/v1/tea --> {"service":"TEA-v1"}
# 8081/api/v2/tea --> {"service":"TEA-v2"}
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-dev-tea
  labels:
    istio-injection: disabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
  namespace: app-dev-tea
  labels:
    app: tea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: tea
        image: giriraj789/cafeshop:v1
        resources:
            limits:
              memory: 200Mi
              cpu: 300m
            requests:
              memory: 100Mi
              cpu: 200m
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: tea
  namespace: app-dev-tea
spec:
  selector:
    app: tea
  ports:
    - name: http-tea
      port: 8081
      targetPort: 8081
      protocol: TCP
