apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: cafeshop-policy
  namespace: sec
spec:
  waf:
    enable: true
    apPolicy: "sec/cafeshop-appolicy"
    securityLogs:
    - enable: true
      apLogConf: "sec/cafeshop-aplogconf"
      logDest: "stderr"
