apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: appdev-vsr
  namespace: appdev
spec:
  host: appdev.giri.local
  upstreams:
  - name: appdev
    service: appdev
    port: 80
  subroutes:
  - path: /
    action:
     pass: appdev
  
