# Date: Feb-2023 Deployment cafeshop imageID: docker pull giriraj789/cafeshop:v1 
# 80 --> {"Service":"CAFE-SHOP"}
# 80/healthz
# 80/righturl
# 80/badurl
---
apiVersion: v1
kind: Namespace
metadata:
  name: appdev
  labels:
    istio-injection: disabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdev
  namespace: appdev
  labels:
    app: appdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdev
  template:
    metadata:
      labels:
        app: appdev
    spec:
      containers:
      - name: appdev
        image: giriraj789/cafeshop:v1
        resources:
            limits:
              memory: 200Mi
              cpu: 300m
            requests:
              memory: 100Mi
              cpu: 200m
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appdev
  namespace: appdev
spec:
  selector:
    app: appdev
  ports:
    - name: http-appdev
      port: 80
      targetPort: 80
      protocol: TCP
---
