---
apiVersion: v1
kind: Service
metadata:
  name: tea
  namespace: appdev
spec:
  selector:
    app: appdev
  ports:
    - name: http-tea
      port: 8081
      targetPort: 8081
      protocol: TCP
---
