apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: appdev-vsr
  namespace: appdev
spec:
  host: appdev.giri.local
  upstreams:
  - name: appdev
    service: appdev
    port: 80
  - name: tea
    service: tea
    port: 8081
  subroutes:
  - path: /
    matches:
    - conditions:
      - variable: $remote_addr
        value: 192.168.1.1
      action:
        pass: appdev
    action:
      pass: tea
  
