apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafeshop-vs
  namespace: nginx-ingress
spec:
  host: cafeshop.giri.local
  policies:
  - name: cafeshop-policy
    namespace: sec
  routes:
  - path: /
    route: app/cafeshop-vsr
  - path: /api/v1/tea
    route: app/tea-vsr
  - path: /api/v1/coffee
    route: app/coffee-vsr
